version: '3.8'
services:
  # api:
  #   build: ./api
  #   container_name: randomreactapp
  #   ports:
  #       -3100:3100
  #   volumes:
  #     -./api/app
  #     -./app/node_modules

  frontend:
    build:
      context: .
    container_name: frontend_client
    ports:
        - '3000:3000'
    environment:
      - HTTP_PROXY=http://proxysrv-in.belcan.com:3128
      - HTTPS_PROXY=http://proxysrv-in.belcan.com:3128
    # volumes:
    #   -./frontend/app
    #   -./app/node_modules
    # volumes:
    #   - ./node_modules:usr/app/node_modules
    #   - . : /usr/app
    stdin_open: true
    tty: true
